---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: ${namespace}
data:
  clusterType: "macbook"
  mgmtClusterName: ${CLUSTER_NAME}
  dnsSuffix: kubernetes.docker.internal
  clusterIP: ${CLUSTER_IP}
  GitHubOrg: ${GITHUB_MGMT_ORG}
  GitHubRepo: ${GITHUB_MGMT_REPO}
  awsAccountId: ac-${AWS_ACCOUNT_ID}
  prefixName: ${PREFIX_NAME}
  awsRegion: ${AWS_REGION}
  awsTagCreator: ${AWS_TAG_creator}
  awsTagCustomer: ${AWS_TAG_customer}
  awsTagProjectGid: "${AWS_TAG_projectGid}"
  userEmail: ${USER_EMAIL}
  vault_url: ${VAULT_ADDR}
  commitUser: ${GITHUB_USER}
